Adding 2022 Support
cms-flaf/Corrections pull request #41
Opened 2024-10-26 16:43 UTC by aebid

2024-11-27 12:02 UTC, kandrosov requested changes

2024-11-27 12:02 UTC, kandrosov commented on triggersRun3.h
> +        }
```suggestion
        } else {
           throw std::runtime_error("Era not supported");
        }
```

2024-11-27 12:18 UTC, aebid commented on mu.py
> +########################################################################################################
I like the hashes ):

2024-12-03 12:25 UTC, kandrosov approved these changes

2024-12-03 12:25 UTC, merged