Ele sf
cms-flaf/Corrections pull request #45
Opened 2024-12-06 14:27 UTC by ahmad3213

2024-12-11 14:28 UTC, kandrosov requested changes
also resolve merge conflicts

2024-12-11 14:28 UTC, kandrosov commented on corrections.h
> +using RVecUL = ROOT::VecOps::RVec<unsigned long>;
```suggestion
```

2024-12-11 14:28 UTC, kandrosov commented on electron.h
> +              }
```suggestion
            if(scale != UncScale::Central
                    && (genMatch==GenLeptonMatch::Electron || genMatch == GenLeptonMatch::TauElectron) ) {
                sf = EleES_->evaluate({"total_uncertainty", static_cast<int>(Electron_seedGain.at(n)), run,
                                       Electron_p4[n].eta(), static_cast<double>(Electron_r9.at(n)),
                                       Electron_p4[n].pt()});
                final_p4[n] *= 1 + static_cast<int>(scale) * sf;
            }
```

2024-12-11 14:28 UTC, kandrosov commented on electron.py
> +        if ( ('2016' in period) or ('2018' in period) or ('2018' in period)):
```suggestion
        if period.startswith('Run2'):
```

2024-12-11 14:28 UTC, kandrosov commented on electron.py
> +            if (period.endswith('Summer22EE')):  EleCorrProducer.year = period.split("_")[0]+"Re-recoE+PromptFG"
add 2023 eras

2024-12-11 14:28 UTC, kandrosov commented on met.py
> +                    df = df.Define(f'MET_p4_{syst_name}_delta', f'MET_p4_{syst_name} - PFMET_p4_{nano}')
take MET name from the config

2024-12-12 22:13 UTC, ahmad3213 commented
> add single electron trigger SF to this PR (same as it was for muons)

This will come later, next week. it will touch different files, so if you can merge this before please

2024-12-13 15:21 UTC, kandrosov requested changes

2024-12-13 15:21 UTC, kandrosov commented on electron.h
>      {
```suggestion
```

2024-12-13 15:51 UTC, kandrosov approved these changes

2024-12-13 15:51 UTC, merged