Bug fix in MuonSF
cms-flaf/Corrections pull request #46
Opened 2024-12-12 12:48 UTC by aebid

Previously, the mu.h getSF functions added a Tau_genMatch branch, I assumed this was a bool of genMatched or not. In my last PR I changed the name to Mu_genMatch for readability.

When making plots, the SF was always 1.0, so I investigated and noticed this 'Tau_genMatch' actually was the generated kind value (looking for 2/4 for TrueMuon/MuonFromTau). This PR is just to update the call of getSF to pass the correct variables.

2024-12-13 20:54 UTC, kandrosov requested changes
To avoid this type of error in the future, I propose not to pass genMatch to `get*MuonSF`  and use it as part of the condition before calling the function.

2024-12-14 10:14 UTC, aebid commented
> To avoid this type of error in the future, I propose not to pass genMatch to `get*MuonSF` and use it as part of the condition before calling the function.

Yeah it is already being used as a bool for calling, but Valeria added it recently so I thought there must be a reason. I can change and remove this arg later and update the PR.

2025-01-22 10:18 UTC, kandrosov commented on mu.h
> +    float getMuonSF(const LorentzVectorM & muon_p4, const float Muon_pfRelIso04_all, const bool Muon_TightId, const float Muon_tkRelIso, const bool Muon_highPtId, UncSource source, UncScale scale, st
why do we need `year` as an argument?

2025-01-22 10:40 UTC, kandrosov approved these changes

2025-01-22 10:50 UTC, merged